# Generated by Django 6.0.3 on 2026-03-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del Productos')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción del producto')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unidad')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='Iva')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado del Producto')),
            ],
        ),
    ]
