# Generated by Django 6.0.3 on 2026-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='Identificación')),
                ('regimen_tributario', models.CharField(max_length=100, verbose_name='Regimen Tributario')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
        ),
    ]
